= Desarrollo de Pruebas de Concepto con Grails
ROOMIE IT SERVICES <http://roomie-it.org/>
VERSIÓN 1.0, Junio 2016
:deckjs_transition: fade
:deckjsdir: deck.js/deck.js-master
:deckjs_theme: swiss
:navigation: 
:menu:
:status:
:goto:
:toc:

== Convenciones generales de código

* Nombrado:
** **Clases:** Comienza con mayúsculas, cada palabra nueva con mayúscula (CamelCase)
** **Variables y atributos:** Sustantivos, la primera con minúsculas
** **Métodos:** Verbos, la primera con minúsculas 

== GRAILS / Introducción

* Framework para desarrollo de aplicaciones Web
** "Full Stack"
*** Trae todos los elementos necesarios para el desarrollo de una aplicación completa
** Configuración por convención
*** Defaults sensibles

== GRAILS / Introducción

* Objetivos principales
** Reutilizar tecnologías Java como Spring y Hibernate en una sola interface
** Modo de desarrollo completo
*** Recarga automática
*** Servidor Web integrado ( Tomcat / Jetty )
* No uso de XML

== GRAILS / Arquitectura General

[shaape]
....

                                                  
          +------------------+------------------+
          |                                     |
          |               FRONTEND              |
          |             Controllers             |
          |         Command / ModelAndView      |
          |                 GSP                 |
          |                                     |
          +-------------------------------------+                                                  
          |                                     |
          |               SERVICES              |
          |             Spring Beans            |
          |          Transaccionalidad          |
          |                                     |
          +-------------------------------------+
          |                                     |
          |            DOMAIN LAYER             |
          |               GORM	                |
          |              Hibernate              |
          |                                     |
          +-------------------------------------+          					 
                             |
                             v
          +------------------+------------------+
          |                                     |
          |                RDBMS                |
          |				    (H2)                |
          |                                     |
          +-------------------------------------+     
....

== GRAILS

* Estructura de directorios / Archivos clave
** /
*** **build.gradle** -> Configuración para la construcción del proyecto proyecto
.... Dependencias
.... Plugins
*** **gradle.properties** -> Elementos llave/valor complemento a build.gradle
*** **grails-app/** -> Componentes principales de Grails
**** **assets/** -> Elementos "estáticos" utilizados por la capa web (CSS/Javascript/imágenes)
**** **conf/** -> Configuración de la aplicación 
..... **application.groovy** -> Parámetros de funcionamiento de la aplicación
..... **application.yml** -> Parámetros de funcionamiento de la aplicación
***** **spring/resources.groovy** -> Beans de Spring adicionales

== GRAILS

* Estructura de directorios / Archivos clave
** /
*** **grails-app/**
**** **controllers/** -> Controladores para Frontend 
**** **domain/** -> Modelo de dominio (GORM)
**** **i18n/** -> Archivos de internacionalización
**** **init/** -> Archivos de inicialización
**** **services/** -> Servicios de negocio
**** **taglib/** -> Librerías de tag utilizables en los GSP
**** **views/** -> GSP (Groovy Server Pages)
** **src/main/groovy** -> Código fuente Groovy / Java diverso

== GRAILS / INSTALACIÓN

* Modo práctico ( SDK Manager ) http://sdkman.io/
[source,bash]
----
curl -s "https://get.sdkman.io" | bash
----
* Modo manual 
** Descargar Kit de Sitio Web ( https://grails.org/download.html )
** Descomprimir
** Agregar variable de Ambiente GRAILS_HOME
[source,bash]
----
export GRAILS_HOME=/path/a/grails
----
** Agregar directorio **bin** al PATH
[source,bash]
----
export PATH=$GRAILS_HOME/bin:$PATH
----

== GRAILS 

* Creación de aplicación
[source,bash]
----
grails create-app <aplicacion>
----

== GRAILS / GORM

* GORM
** Groovy Object / Relational Mapping
** Integración entre el modelo OO y las bases de datos relacionales
** Basado en Hibernate
** Actualmente soporta modelos no relacionales
** Aprovechas las características dinámicas de Groovy 

== GRAILS / GORM

* Modelo de Dominio
** Modelo conceptual de todos los temas relacionados con un problema específico
*** Atributos
*** Papeles
*** Relaciones
** Modelo anémico
*** Simple mapeo de tablas a objetos
** Modelo Enriquecido
*** Colección de objetos que expone comportamiento
*** Aplican patrones de diseño
*** Se enfocan en el "que", no en el "como"

== GRAILS / GORM

* Modelo de dominio
** Representado como clases Groovy
** Describen el modelo de información a persistir
** Contienen reglas para el comportamiento de sus atributos (Constraints)
[source,bash]
----
grails create-domain-class <package.clase>
----

== GRAILS / GORM

* Práctica 3-A
** Plantear el modelo de dominio para una aplicación de facturación
** Cada quien una clase
** 15 minutos
** Probar el almacenado en Base de datos
[source,groovy]
----
objeto.save()
----
** Mostrar el listado de objetos almacenados:
[source,groovy]
----
Clase.list()
----
** Obtener un objeto por su Id:
[source,groovy]
----
Clase.get(<id>)
----

== GRAILS / GORM

* Constraints
** Reglas de negocio que delimitan el comportamiento de los atributos en el modelo de dominio
** Closure estático dentro de la clase:
[source,groovy]
----
class Modelo{
	String modelo
	String descripcion
	
	static constraints = {
		modelo(maxSize:25)
		descripcion(nullable:true,matches: "[a-zA-Z]+")		
	}
}
----

== GRAILS / GORM

* Constraints
** Principales constraints:
*** **nullable** -> Indica si un valor puede ser nulo o no
*** **email** -> Que el valor coincida con un correo electrónico (formato)
*** **matches** -> Se asegura que el atributo coincida con la expresión regular planteada
*** **minSize / maxSize** -> Delimita el tamaño de un string
*** **min / max** -> Delimita el valor mínimo / máximo de un atributo
*** **unique** -> Verifica que un valor o grupo de valores no se repita
*** **validator** -> Permite la creación de una validación personalizada

== GRAILS / GORM

* Práctica 3-B
** Aplicar la mayor parte de los constraints al modelo de dominio
** 15 minutos

== Grails / GORM

* Relaciones
** Uno a uno
*** Se aplica cuando una clase es propiedad de otra:
[source,groovy]
----
class Hotel{
	String nombre
	Recepcion recepcion
}
class Recepcion{
	String ubicacion
	Hotel hotel
}
----
*** Se recomienda que una clase sea la que domine a la otra mediante el atributo **belongsTo**
[source,groovy]
----
class Hotel{
	String nombre
	Recepcion recepcion
}
class Recepcion{
	String ubicacion
	static belongsTo = [hotel:Hotel]
}
----

== Grails / GORM

* Relaciones
** Uno a muchos
*** Se recomienda utilizar el atributo **hasMany**
*** Se recomienda que la clase derivada también tenga un atributo **belongsTo**
[source,groovy]
----
class Hotel{
	String nombre
	Recepcion recepcion
	static hasMany = [habitaciones:Habitacion]
}
class Habitacion{
	int piso
	int numero
	static belongsTo = [hotel:Hotel]
}
----

== Grails / GORM

* Relaciones
** Muchos a muchos
*** Ambas clases tendrán el atributo **hasMany**
*** Una deberá llevar el atributo **belongsTo** (Puede indicar solo la clase)
[source,groovy]
----
class Hotel{
	String nombre
	Recepcion recepcion
	static hasMany = [habitaciones:Habitacion,huespedes.Huesped]
}
class Huesped{
	String nombre
	static hasMany = [hoteles:Hotel]
	static belongsTo = Hotel
}
----

== GRAILS / GORM

* Práctica 3-C
** Relacionar el modelo de dominio entre sí
** 15 minutos



** Criteria queries

* Grails (Cont.)
** Capa de Negocio
*** Servicios / Transaccionalidad
*** Integración con Spring
** Capa MVC
*** Controllers
*** Interceptors
*** Groovy Server Pages (GSP)

** Sobrecarga de operadores
** Metaprogrammings
** Builders
** XML y JSON

